name: Build and Test E2E

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Nix
      uses: cachix/install-nix-action@v27

    - name: Install dependencies
      run: sudo apt update && sudo apt install -y protoc-gen-go
    - name: Install go dependencies
      run: make install-deps

    - name: Build
      run: make build

    - name: Test e2e
      run: make e2e

    - name: Upload build
      uses: actions/upload-artifact@v4
      with:
        name: go-generate-fast
        path: bin/go-generate-fast
        retention-days: 7
