name: Lint

on: [pull_request]

permissions:
  contents: read

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Nix
        uses: cachix/install-nix-action@v27

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
