name: Test

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Nix
      uses: cachix/install-nix-action@v27

    - uses: rrbutani/use-nix-shell-action@v1

    - name: Install go dependencies
      run: make install-deps

    - name: Test
      run: make test
